### ISSUE TITLE
examplegl

### ISSUE THREAD

**Issue by fujunustc** [OpenHMD/OpenHMD#142]
I compile the sample codes in `xxx/example/opengl` but it doesn't render image to Oculus Rift cv1 , just seeing the desktop in HMD. #109 

The Environment:

ubuntu16.04 LTS

GTX1050Ti 

Oculus Rift cv1

Extension:

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"

    Option "AllowHMD" "yes"
EndSection

**Comment by rfht** [comment]
For all I know the opengl example works only in extended mode (see [issue #109](https://github.com/OpenHMD/OpenHMD/issues/109).

While I don't have an nVidia, it seems to me based on the [Xorg documentation](http://us.download.nvidia.com/XFree86/Linux-x86/378.09/README/xconfigoptions.html) that you need to disable the `"AllowHMD"` option in order to use extended mode. After restarting X11, the HMD should show up as a secondary monitor. I tend to use arandr, go to Outputs, and then enable the one that the HMD is connected to (not done with a CV1, but with others).

When openglexample runs, I just move the window over to where the HMD's display is in relationship to the main display (as shown in arandr).

**Comment by TheOnlyJoey** [comment]
OpenHMD does not handle window placement at this point. You will have to manually move the window to the correct display, or implement this yourself with SDL2 or similar.
