### ISSUE TITLE
openHMD opengl example wrong display

### ISSUE THREAD

**Issue by jamesmagnus** [OpenHMD/OpenHMD#161]
Hi, I tried to run the opengl example but it displays on my computer screen and not in the oculus rift. Are there any options or configuration to select the correct the display ?

The sensors work well. I have a nvidia gtx 970 and I'm using the HDMI port on the graphic card.

**Comment by alex9099** [comment]
I guess that it starts where you have the terminal running, you need to move the window to the hmd display

**Comment by jamesmagnus** [comment]
The problem is that there isn't any hmd display, the oculus is not in extended mode but in direct mode I think.

**Comment by alex9099** [comment]
is your monitor connected to the dedicated gpu (nvidia) or to the igpu? Also are you on windows(if so do you have oculus drivers?)?

**Comment by robmyers** [comment]
I see this behaviour with a dedicated GPU on Debian.

**Comment by jamesmagnus** [comment]
Everything is connected to the dedicated GPU, I don't have graphic in my CPU. I'm on Linux Ubuntu 16

**Comment by TheOnlyJoey** [comment]
So there is no logic in OpenHMD to dictate where it is launching, this is currently determined by the application.
People have made setups with SDL2 detecting screens and automatically launching on the right display when in extended mode, would be cool if someone could build that into our openglexample.

Otherwise direct mode through vulkan is currently the way to go (on linux).

**Comment by fluffrabbit** [comment]
Not to impose, but will there be a Vulkan example?

**Comment by robmyers** [comment]
See also - https://github.com/OpenHMD/OpenHMD/issues/114
