### ISSUE TITLE
Support for VRPN?

### ISSUE THREAD

**Issue by mwbogucki** [OpenHMD/OpenHMD#320]
Looking for support of VRPN, so other devices, or trackers can be used with OpenHMD.  My HMDs are DIY'ed, with no built-in trackers.  I rely on a Polhemus Fastrak for tracking data. 
I'd think adding support for VRPN would increase the use of OpenHMD; since they've done a bulk of device-support. 
Thank you.

**Comment by TheOnlyJoey** [comment]
OpenHMD tries to be dependency-less as much as possible. and we do not Link to any external services or drivers. It is totally possible to make a wrapper of some kind (Like SteamVR-OpenHMD does for SteamVR or Monado does for OpenXR) if you want to use OpenHMD drivers in VRPN, or write a custom OpenHMD VRPN driver to use VRPN devices in OpenHMD. Since we have a compatible ABI/API its easy to use a custom driver in supported applications without compatibility issues.
